// <auto-generated />
namespace OOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pracownik_komisja_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pracownik_komisja_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "202403131121432_pracownik_komisja_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
