// <auto-generated />
namespace OOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migracja14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracja14));
        
        string IMigrationMetadata.Id
        {
            get { return "202404150830562_migracja14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
