// <auto-generated />
namespace OOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ankietaState_komisjaTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ankietaState_komisjaTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202403122254145_ankietaState_komisjaTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
