namespace OOP.Migrations
{
    using Faker;
    using Microsoft.AspNet.Identity.EntityFramework;
    using Microsoft.AspNet.Identity;
    using OOP.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<OOP.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(OOP.Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.

            //dajcie tu jakiś warunek ktory się nie spełni bo  po update całą baze bedzie wypełniac (dane mogą się powtarzać) - szkoda zasobów :D
            if (true)
            {
                return;
            }
            var adresy = new List<Adres>();
            var users = new List<ApplicationUser>();
            var ankiety = new List<Ankieta>();
            var dzialy = new List<Dzial>();

            var komisje = new List<Komisja>();
            var ocena = new List<Ocena>();
            var polaAnkiet = new List<PoleAnkiety>();
            var osiagniecie = new List<Osiagniecie>();
            var pracaDyplomowe = new List<PracaDyplomowa>();
            var pracownicy = new List<Pracownik>();
            var stronaAnkieties = new List<StronaAnkiety>();
            var schematy = new List<Schemat>();

            string[] nazwydzialow = {"DSP",
                                     "DN",
                                     "BRiPM",
                                     "OWI",
                                     "Bds.Wm",
                                     "CSSDIR",
                                     "DJK",
                                     "DP",};

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            int n = 1;
            foreach (var nazwaDzialu in nazwydzialow)
            {
                dzialy.Add(new Dzial { Nazwa = nazwaDzialu , DzialID = n++});
            }
            //Dzial DSP
            schematy.Add(new Schemat { Name = "Członkostwo w zespołach eksperckich powołanych przez organy lub instytucje państwowe oraz instytucje zagraniczne lub międzynarodowe (za każdy rok)", DzialID = 1, IsOrganizational = false, MaxPoints = "8" });
            schematy.Add(new Schemat { Name = "Działalność w zespołach i panelach instytucji centralnych, np. Rady Doskonałości Naukowej, Narodowym Centrum Nauki i Narodowym Centrum Badań i Rozwoju (uwzględnia się proporcjonalnie do czasu pełnienia funkcji)", DzialID = 1, IsOrganizational = false, MaxPoints = "13 / rocznie" });
            schematy.Add(new Schemat { Name = "Uzyskanie certyfikatu z języka obcego na poziomie wyższym niż B2 – jednorazowo", DzialID = 1, IsOrganizational = true, MaxPoints = "8" });
            schematy.Add(new Schemat { Name = "Pełnienie funkcji prorektora / dziekana lub dyrektora instytutu / prodziekana / kierownika: katedry, zakładu, studium / zastępcy kierownika: katedry, zakładu, studium lub kierownika zespołu, pracowni (określa bezpośredni przełożony)", DzialID = 1, IsOrganizational = true, MaxPoints = "32/24/16/8/4" });
            schematy.Add(new Schemat { Name = "Pełnienie funkcji pełnomocnika rektora lub dziekana (określa rektor lub dziekan)", DzialID = 1, IsOrganizational = true, MaxPoints = "do 8" });
            schematy.Add(new Schemat { Name = "Pełnienie funkcji kierownika studiów doktoranckich/ Dyrektora Szkoły Doktorskiej (określa dziekan)", DzialID = 1, IsOrganizational = true, MaxPoints = "do 15" });
            schematy.Add(new Schemat { Name = "Udział z wyboru we władzach centralnych towarzystw naukowych / związków i organizacji branżowych krajowych / regionalnych", DzialID = 1, IsOrganizational = true, MaxPoints = "16/12/8" });
            schematy.Add(new Schemat { Name = "Członkostwo w organach kolegialnych Uczelni / wydziału oraz komisjach powołanych przez te organy", DzialID = 1, IsOrganizational = true, MaxPoints = "4" });
            schematy.Add(new Schemat { Name = "Członkostwo w zespołach i komisjach powołanych zarządzeniem rektora, członkostwo w zarządzie fundacji lub radzie nadzorczej spółki utworzonej przez Uczelnię", DzialID = 1, IsOrganizational = true, MaxPoints = "4" });
            schematy.Add(new Schemat { Name = "Uczestnictwo w Uczelnianej / Wydziałowej Komisji ds. Jakości Kształcenia", DzialID = 1, IsOrganizational = true, MaxPoints = "12/8" });
            schematy.Add(new Schemat { Name = "Członkostwo w komisji rekrutacyjnej – uczelnianej / wydziałowej (za każdą rekrutację), przewodniczący / sekretarz dodatkowo 4 pkt.", DzialID = 1, IsOrganizational = true, MaxPoints = "4/8" });
            schematy.Add(new Schemat { Name = "Przewodniczenie komitetom, zarządom, sekcjom, zespołom, organom i komisjom, o których mowa w pkt. IV.4- IV.8 dodatkowo 4 pkt", DzialID = 1, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Członkostwo we władzach zagranicznych lub międzynarodowych towarzystw, organizacji i instytucji naukowych lub artystycznych, których członkowie pochodzą co najmniej z 10 państw ", DzialID = 1, IsOrganizational = true, MaxPoints = "8" });
            schematy.Add(new Schemat { Name = "Członkostwo w PAN / członkostwo w komitecie / członek stowarzyszony z sekcją PAN, ekspert (uwzględnia się jednorazowo w okresie oceny proporcjonalnie do czasu pełnienia funkcji)", DzialID = 1, IsOrganizational = true, MaxPoints = " 30/20/4" });
            schematy.Add(new Schemat { Name = "Działalność w zespołach i panelach instytucji centralnych, np. w Polskiej Komisji Akredytacyjnej, Radzie Nauki, Radzie Głównej Nauki i Szkolnictwa Wyższego / instytucjach regionalnych (uwzględnia się jednorazowo  w okresie oceny proporcjonalnie do czasu pełnienia funkcji)", DzialID = 1, IsOrganizational = true, MaxPoints = " 25/8" });
            schematy.Add(new Schemat { Name = "Nagroda prezydenta, premiera / ministra / marszałka województwa, wojewody, prezydenta miasta ", DzialID = 1, IsOrganizational = true, MaxPoints = " 50/35/20" });
            schematy.Add(new Schemat { Name = "Uzyskanie nagrody innej niż wymieniona w pkt. V.1, na poziomie międzynarodowym / krajowym / regionalnym", DzialID = 1, IsOrganizational = true, MaxPoints = " 40/30/10" });
            schematy.Add(new Schemat { Name = "Nagroda rektora indywidualna / zespołowa oraz nagrody przyznawane przez krajowe i zagraniczne instytucje edukacyjne", DzialID = 1, IsOrganizational = true, MaxPoints = " 12/4" });

            //Dzial DN
            schematy.Add(new Schemat { Name = "Uzyskanie tytułu profesora", DzialID = 2, IsOrganizational = false, MaxPoints = "160" });
            schematy.Add(new Schemat { Name = "Uzyskanie stopnia doktora habilitowanego", DzialID = 2, IsOrganizational = false, MaxPoints = "120" });
            schematy.Add(new Schemat { Name = "Uzyskanie stopnia doktora", DzialID = 2, IsOrganizational = false, MaxPoints = "60" });
            schematy.Add(new Schemat { Name = "Pełnienie funkcji promotora w Uczelni/poza Uczelnią (max. przez okres 3 lat) w postępowaniu o nadanie stopnia doktora pozytywnie zakończonym w Uczelni/poza Uczelnią, dodatkowo 10/5 pkt. za pracę wyróżnioną", DzialID = 2, IsOrganizational = false, MaxPoints = "8/4; 40/20" });
            schematy.Add(new Schemat { Name = "Pełnienie funkcji promotora pomocniczego (max. przez okres 3 lat) w postępowaniu o nadanie stopnia doktora/pozytywnie zakończonym, dodatkowo 4 pkt. za pracę wyróżnioną", DzialID = 2, IsOrganizational = false, MaxPoints = "4/12" });
            schematy.Add(new Schemat { Name = "W projektach obejmujących badania naukowe lub prace rozwojowe, finansowanych w trybie konkursowym: \n - przez Europejską Radę ds Badań Naukowych (European Research Council) (W=5, gdzie  W - współczynnik rodzaju finansowania) \n - w ramach programów ramowych w zakresie wspierania badań i innowacji Unii Europejskiej, albo w ramach programów związanych z wdrażaniem tych programów (W=2), \n -  przez instytucje zagraniczne lub organizacje międzynarodowe (W=1,5), \n - ze środków funduszy strukturalnych Unii Europejskiej albo z niepodlegających zwrotowi środków z pomocy udzielonej przez państwa członkowskie Europejskiego Porozumienia o Wolnym Handlu (EFTA), albo innych źródeł zagranicznych nie podlegających zwrotowi (W=1,5),\n - w ramach Narodowego Programu Rozwoju Humanistyki (W=0,5), \n kierownik i członkowie zespołu przygotowującego wniosek aplikacyjny otrzymują jednorazowo:", DzialID = 2, IsOrganizational = false, MaxPoints = "nie dotyczy Działu Nauki" });
            schematy.Add(new Schemat { Name = "1) 5xW punktów - za złożenie wniosku aplikacyjnego; punkty przyznawane jednorazowo na podstawie podziału dokonanego przez kierownikazespołu, proporcjonalnie do wkładu pracy,", DzialID = 2, IsOrganizational = false, MaxPoints = "nie dotyczy Działu Nauki" });
            schematy.Add(new Schemat { Name = "2) 30xW punktów - w przypadku otrzymania pozytywnej oceny formalno-merytorycznej złożonego wniosku; punkty przyznawane jednorazowo na podstawie podziału dokonanego przez kierownika zespołu, proporcjonalnie do wkładu pracy,    ", DzialID = 2, IsOrganizational = false, MaxPoints = "nie dotyczy Działu Nauki" });
            schematy.Add(new Schemat { Name = "3) 2 pkt. za każde 50 tys. zł przyznanych funduszy,*\r\nktórego liderem jest Uczelnia lub inny podmiot należący do systemu\r\nszkolnictwa wyższego i nauki lub 2 pkt. za 25 tys. zł przyznanych funduszy*, którego\r\nliderem jest podmiot nienależący do systemu szkolnictwa wyższego i nauki xW punktów - za uzyskanie projektu; punkty\r\nmogą być rozdzielone proporcjonalnie do czasu realizacji projektu w\r\ndanym roku oraz podzielone proporcjonalnie do wkładu pracy w przygotowanie\r\nwniosku w danym roku na podstawie podziału dokonanego przez kierownika zespołu                *wartość projektu ogólem, jeżeli Uczelnia jest samodzielnym wykonawcą lub liderem, lub wartość realizowanych zadań, jeżeli Uczelnia jest członkiem konsorcjum      ", DzialID = 2, IsOrganizational = false, MaxPoints = "nie dotyczy Działu Nauki" });
            schematy.Add(new Schemat { Name = "Za złożenie wniosku o realizację projektu finansowanego lub zarządzanego przez\r\nNCN, NCBiR, MNiSW o wartości do 1 mln zł / powyżej 1 mln zł − kierownik\r\ndokonuje podziału 2/4 pkt. proporcjonalnie do wkładu pracy zespołu;                                                                      ", DzialID = 2, IsOrganizational = false, MaxPoints = "wypełnia Dział Nauki" });
            schematy.Add(new Schemat { Name = " Za uzyskanie projektu zespół otrzymuje 2 pkt. za każde 50 tys. zł przyznanych\r\nfunduszy*, którego liderem jest Uczelnia lub inny podmiot należący do systemu\r\nszkolnictwa wyższego i nauki lub 2 pkt. za 25 tys. zł przyznanych funduszy*, którego\r\nliderem jest podmiot nienależący do systemu szkolnictwa wyższego i nauki. Punkty\r\nmogą być przyznane jednorazowo lub proporcjonalnie do czasu realizacji projektu w\r\ndanym roku oraz podzielone proporcjonalnie do wkładu pracy w przygotowanie\r\nwniosku. Podziału punktów dokonuje kierownik zespołu", DzialID = 2, IsOrganizational = false, MaxPoints = "wypełnia Dział Nauki" });
            schematy.Add(new Schemat { Name = "Za udział w realizacji projektów obejmujących badania naukowe lub prace rozwojowe,\r\npracach umownych, wdrożeniach i licencjach, pracownik uzyskuje 2 pkt. za każde\r\n5 tys. zł wynagrodzenia brutto (wartość umowy z Uczelnią) z uwzględnieniem\r\nwspółczynnika „W” zależnego od źródła finansowania:", DzialID = 2, IsOrganizational = false, MaxPoints = "wypełnia Dział Nauki pkt 5 i 6" });
            schematy.Add(new Schemat { Name = "1) przez Europejską Radę ds. Badań Naukowych (European Research Council) (W=5),", DzialID = 2, IsOrganizational = false, MaxPoints = "nie dotyczy Działu Nauki" });
            schematy.Add(new Schemat { Name = "2) w ramach programów ramowych w zakresie wspierania badań i innowacji Unii Europejskiej, albo w ramach programów związanych z wdrażaniem tych programów (W=2),", DzialID = 2, IsOrganizational = false, MaxPoints = "nie dotyczy Działu Nauki" });
            schematy.Add(new Schemat { Name = "3)  przez instytucje zagraniczne lub organizacje międzynarodowe (W=1,5),  ", DzialID = 2, IsOrganizational = false, MaxPoints = "nie dotyczy Działu Nauki" });
            schematy.Add(new Schemat { Name = "4) ze środków funduszy strukturalnych Unii Europejskiej albo z niepodlegających zwrotowi środków z pomocy udzielonej przez państwa członkowskie Europejskiego Porozumienia o Wolnym Handlu (EFTA), albo innych źródeł zagranicznych nie podlegających zwrotowi (W=1,5),     ", DzialID = 2, IsOrganizational = false, MaxPoints = "nie dotyczy Działu Nauki" });
            schematy.Add(new Schemat { Name = "5) przez MNiSW, NCBR i NCN (W=1),", DzialID = 2, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "6) w ramach Narodowego Programu Rozwoju Humanistyki (W=0,5)", DzialID = 2, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Kierownik i członkowie zespołu za realizację projektu obejmującego badania naukowe lub prace rozwojowe, w tym: \r\n- komercjalizację wyników badań naukowych lub prac rozwojowych, lub know-how związanego z tymi wynikami; \r\n- usługi badawcze świadczone na zlecenie podmiotów nienależących do systemu szkolnictwa wyższego i nauki: \r\notrzymują 2 pkt. za 5 tys. zł sumy przychodów osiągniętych w okresie objętym oceną przez Uczelnię, w ramach dyscypliny ocenianej w Uczelni lub zadeklarowanej przez pracownika, lub know-how związanego z tymi wynikami lub otrzymują 2 pkt. za 10 tys. zł sumy przychodów osiągniętych w okresie objętym oceną przez inny podmiot utworzony przez Uczelnię, w tym Instytut Innowacji i Technologii Politechniki Białostockiej i spółki typu spin-off utworzone przez Uczelnię, w celu komercjalizacji wyników badań naukowych lub prac rozwojowych prowadzonych w Uczelni, w ramach dyscypliny ocenianej w Uczelni lub zadeklarowanej przez pracownika, lub know-how związanego z tymi wynikami. \r\nPunkty mogą być rozdzielone proporcjonalnie do czasu realizacji projektu w danym roku. Kierownik dokonuje podziału punktów proporcjonalnie do wkładu pracy zespołu", DzialID = 2, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Opracowanie recenzji w postępowaniu habilitacyjnym, w postępowaniu o nadanie tytułu profesora oraz tytułu doktora honoris causa, promotorstwo w postępowaniu o nadanie tytułu doktora honoris causa", DzialID = 2, IsOrganizational = false, MaxPoints = "16" });
            schematy.Add(new Schemat { Name = "Udział w komisji habilitacyjnej w charakterze przewodniczącego/ sekretarza/ członka/ recenzenta", DzialID = 2, IsOrganizational = false, MaxPoints = "8/6/4/4" });
            schematy.Add(new Schemat { Name = "Opracowanie recenzji wydawniczej monografii, rozprawy naukowej lub recenzji pracy doktorskiej", DzialID = 2, IsOrganizational = false, MaxPoints = "12" });
            schematy.Add(new Schemat { Name = "Opracowanie recenzji artykułu w czasopiśmie posiadającym Impact Factor (maksymalnie 10 pkt. rocznie)", DzialID = 2, IsOrganizational = false, MaxPoints = "1" });
            schematy.Add(new Schemat { Name = "Opracowanie recenzji projektu w konkursach krajowych / międzynarodowych", DzialID = 2, IsOrganizational = false, MaxPoints = "2/4" });
            schematy.Add(new Schemat { Name = "Członkostwo pracownika w komitecie redakcyjnym czasopisma umieszczonego w wykazie czasopism naukowych MNiSW (za każdy rok)"  , DzialID = 2, IsOrganizational = false, MaxPoints = "4" });
            schematy.Add(new Schemat { Name = "Redaktor naukowy wydawnictw (w dyscyplinie) (za każdy rok)", DzialID = 2, IsOrganizational = false, MaxPoints = "5" });
            schematy.Add(new Schemat { Name = "Sekretarz naukowy czasopisma wydawanego w Uczelni (za każdy opracowany numer czasopisma)", DzialID = 2, IsOrganizational = false, MaxPoints = "4" });
           
            schematy.Add(new Schemat { Name = " - przewodniczący komitetu organizacyjnego", DzialID = 2, IsOrganizational = true, MaxPoints = "do 30" });
            schematy.Add(new Schemat { Name = " - sekretarz lub zastępca przewodniczącego komitetu organizacyjnego", DzialID = 2, IsOrganizational = true, MaxPoints = "do 20" });
            schematy.Add(new Schemat { Name = " - pozostali członkowie komitetu organizacyjnego", DzialID = 2, IsOrganizational = true, MaxPoints = "do 15" });
            schematy.Add(new Schemat { Name = " - przewodniczący komitetu organizacyjnego", DzialID = 2, IsOrganizational = true, MaxPoints = "do 16" });
            schematy.Add(new Schemat { Name = " - sekretarz lub zastępca przewodniczącego komitetu organizacyjnego", DzialID = 2, IsOrganizational = true, MaxPoints = "do 14" });
            schematy.Add(new Schemat { Name = " - pozostali członkowie komitetu organizacyjnego", DzialID = 2, IsOrganizational = true, MaxPoints = "do 10" });
            schematy.Add(new Schemat { Name = "Opracowanie recenzji wydawniczej skryptu lub podręcznika", DzialID = 2, IsOrganizational = true, MaxPoints = "8" });

            //Dział BRiPM

            schematy.Add(new Schemat { Name = "W projektach obejmujących badania naukowe lub prace rozwojowe, finansowanych w trybie konkursowym:\r\n- przez Europejską Radę ds. Badań Naukowych (European Research Council) (W=5, gdzie W - współczynnik rodzaju finansowania),\r\n- w ramach programów ramowych w zakresie wspierania badań i innowacji Unii Europejskiej, albo w ramach programów związanych z wdrażaniem tych programów (W=2),\r\n- przez instytucje zagraniczne lub organizacje międzynarodowe (W=1,5),\r\n-  ze środków funduszy strukturalnych Unii Europejskiej albo z niepodlegających zwrotowi środków z pomocy udzielonej przez państwa członkowskie Europejskiego Porozumienia o Wolnym Handlu (EFTA) albo innych źródeł zagranicznych nie podlegających zwrotowi (W=1,5),\r\n- w ramach Narodowego Programu Rozwoju Humanistyki (W=0,5),\r\nkierownik i członkowie zespołu przygotowującego wniosek aplikacyjny otrzymują jednorazowo:\r\n1) 5×W punktów - za złożenie wniosku aplikacyjnego; punkty przyznawane jednorazowo na podstawie podziału dokonanego przez kierownika zespołu, proporcjonalnie do wkładu pracy,\r\n2) 30×W punktów - w przypadku otrzymania pozytywnej oceny formalno-merytorycznej złożonego wniosku; punkty przyznawane jednorazowo na podstawie podziału dokonanego przez kierownika zespołu, proporcjonalnie do wkładu pracy,\r\n3) 2 pkt. za każde 50 tys. zł przyznanych funduszy*, którego liderem jest Uczelnia lub inny podmiot należący do systemu szkolnictwa wyższego i nauki lub 2 pkt.za 25 tys. zł przyznanych funduszy*, którego liderem jest podmiot nienależący do systemu szkolnictwa wyższego i nauki × W punktów - za uzyskanie projektu; punkty mogą być rozdzielone proporcjonalnie do wkładu pracy w \r\nprzygotowanie wniosku w danym roku na podstawie podziału dokonanego przez kierownika zespołu\r\n* wartość projektu ogółem, jeżeli Uczelnia jest samodzielnym wykonawcą lub liderem, lub wartość realizowanych zadań, jeżeli Uczelnia jest członkiem konsorcjum\r\n", DzialID = 3, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "1) Za złożenie wniosku o realizację projektu finansowanego lub zarządzanego przez NCN, NCBiR, MNiSW o wartości do 1 mln zł / powyżej 1 mln zł − kierownik dokonuje podziału 2/4 pkt. proporcjonalnie do wkładu pracy zespołu;\r\n2) Za uzyskanie projektu zespół otrzymuje 2 pkt. za każde 50 tys. zł przyznanych funduszy*, którego liderem jest Uczelnia lub inny podmiot należący do systemu szkolnictwa wyższego i nauki lub 2 pkt. za 25 tys. zł przyznanych funduszy*, którego liderem jest podmiot nienależący do systemu szkolnictwa wyższego i nauki. Punkty mogą być przyznane jednorazowo lub proporcjonalnie do czasu realizacji projektu w danym roku oraz podzielone proporcjonalnie do wkładu pracy w przygotowanie \r\nwniosku. Podziału punktów dokonuje kierownik zespołu\r\n* wartość projektu ogółem, jeżeli Uczelnia jest samodzielnym wykonawcą lub liderem, \r\nlub wartość realizowanych zadań, jeżeli Uczelnia jest członkiem konsorcjum", DzialID = 3, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Za udział w realizacji projektów obejmujących badania naukowe lub prace rozwojowe, pracach umownych, wdrożeniach i licencjach, pracownik uzyskuje 2 pkt. za każde 5 tys. zł wynagrodzenia brutto (wartość umowy z Uczelnią) z uwzględnieniem współczynnika „W” zależnego od źródła finansowania:\r\n1) przez Europejską Radę ds. Badań Naukowych (European Research Council) (W=5),\r\n2) w ramach programów ramowych w zakresie wspierania badań i innowacji Unii Europejskiej, albo w ramach programów związanych z wdrażaniem tych programów (W=2),\r\n3) przez instytucje zagraniczne lub organizacje międzynarodowe (W=1,5),\r\n4) ze środków funduszy strukturalnych Unii Europejskiej albo z niepodlegających zwrotowi środków z pomocy udzielonej przez państwa członkowskie Europejskiego Porozumienia o Wolnym Handlu (EFTA) albo innych źródeł zagranicznych nie podlegających zwrotowi (W=1,5),\r\n5) przez MNiSW, NCBR i NCN (W=1),\r\n6) w ramach Narodowego Programu Rozwoju Humanistyki (W=0,5)", DzialID = 3, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Kierownik i członkowie zespołu za realizację projektu obejmującego badania naukowe lub prace rozwojowe, w tym:\r\n- komercjalizację wyników badań naukowych lub prac rozwojowych lub know-how związanego z tymi wynikami;\r\n- usługi badawcze świadczone na zlecenie podmiotów nienależących do systemu szkolnictwa wyższego i nauki:otrzymują 2 pkt. za 5 tys. zł sumy przychodów osiągniętych w okresie objętym oceną przez Uczelnię, w ramach dyscypliny ocenianej w Uczelni lub zadeklarowanej przez \r\npracownika, lub know-how związanego z tymi wynikami lub otrzymują 2 pkt. za10 tys. zł sumy przychodów osiągniętych w okresie objętym oceną przez inny podmiot utworzony przez Uczelnię, w tym Instytut Innowacji i Technologii Politechniki Białostockiej i spółki typu spin-off utworzone przez Uczelnię, w celu komercjalizacji wyników badań naukowych lub prac rozwojowych prowadzonych w \r\nUczelni, w ramach dyscypliny ocenianej w Uczelni lub zadeklarowanej przez pracownika, lub know-how związanego z tymi wynikami.\r\nPunkty mogą być rozdzielone proporcjonalnie do czasu realizacji projektu w danym roku. Kierownik dokonuje podziału punktów proporcjonalnie do wkładu pracy zespołu", DzialID = 3, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "1) Za złożenie wniosku o realizację projektu finansowanego w trybie konkursowym o wartości do 1 mln zł / powyżej 1 mln zł − kierownik dokonuje podziału 7/10 punktów proporcjonalnie do wkładu pracy zespołu;\r\n2) Za uzyskanie projektu zespół otrzymuje 2 pkt. za każde 50 tys. zł przyznanych funduszy*, którego liderem jest Uczelnia lub inny podmiot należący do systemu szkolnictwa wyższego i nauki lub 2 pkt. za 25 tys. zł przyznanych funduszy*, którego liderem jest podmiot nienależący do systemu szkolnictwa wyższego i nauki. Punkty mogą być przyznane jednorazowo lub proporcjonalnie do czasu \r\nrealizacji projektu w danym roku oraz podzielone proporcjonalnie do wkładu pracy w przygotowanie wniosku. Podział punktów dokonuje kierownik zespołu;\r\n3) Za udział w realizacji projektów pracownik uzyskuje 2 pkt. za każde 3 tys. zł wynagrodzenia brutto (wartość umowy z Uczelnią) \r\n* wartość projektu ogółem, jeżeli PB jest samodzielnym wykonawcą lub liderem, lub wartość realizowanych zadań, jeżeli Uczelnia jest członkiem konsorcjum", DzialID = 3, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Koordynator / koordynator wydziałowy lub koordynator zadania / członek zespołu w projekcie dydaktycznym lub inwestycyjnym finansowanym ze środków zewnętrznych (za każdy miesiąc) 4/2/1", DzialID = 3, IsOrganizational = true, MaxPoints = "" });


            //Dział OWI
            schematy.Add(new Schemat { Name = "Patenty: 1) europejskie albo przyznane Uczelni za granicą w co najmniej jednym z państw należących do Organizacji Współpracy Gospodarczej i Rozwoju pod warunkiem, że wynalazek został zgłoszony również w Urzędzie Patentowym Rzeczypospolitej Polskiej; 2) przyznane Uczelni przez Urząd Patentowy Rzeczypospolitej Polskiej; 3) o których mowa w pkt 1 albo 2, przyznane innemu podmiotowi, jeżeli autorem albo współautorem wynalazku, na który patent został przyznany, jest pracownik Uczelni", DzialID = 4, IsOrganizational = false, MaxPoints = "100/75/50" });
            schematy.Add(new Schemat { Name = "Wyłączne prawa hodowcy do odmiany roślin przyznane Uczelni przez Centralny Ośrodek Badania Odmian Roślin Uprawnych albo Wspólnotowy Urząd Ochrony Roślin (Community Plant Variety Office)", DzialID = 4, IsOrganizational = false, MaxPoints = "50" });
            schematy.Add(new Schemat { Name = "Prawa ochronne na wzór użytkowy przyznane Uczelni przez Urząd Patentowy Rzeczypospolitej Polskiej albo za granicą", DzialID = 4, IsOrganizational = false, MaxPoints = "30" });
            schematy.Add(new Schemat { Name = "Zgłoszenie wynalazku przez Uczelnię za granicą lub w Urzędzie Patentowym RP lub zgłoszenie wynalazku przez inny podmiot, gdy pracownik Uczelni jest współautorem - w zależności od sposobu zgłoszenia - 10/7,5/5 pkt liczba punktów / liczbę pracowników i doktorantów Uczelni proporcjonalnie do ich udziału", DzialID = 4, IsOrganizational = false, MaxPoints = "10/7.5/5" });

            //Dział Bds.WM

            schematy.Add(new Schemat { Name = "W projektach obejmujących badania naukowe lub prace rozwojowe, finansowanych w trybie konkursowym:\r\n- przez Europejską Radę ds. Badań Naukowych (European Research Council) (W=5, gdzie W - współczynnik rodzaju finansowania),\r\n- w ramach programów ramowych w zakresie wspierania badań i innowacji Unii Europejskiej, albo w ramach programów związanych z wdrażaniem tych programów (W=2),\r\n- przez instytucje zagraniczne lub organizacje międzynarodowe (W=1,5),\r\n-  ze środków funduszy strukturalnych Unii Europejskiej albo z niepodlegających zwrotowi środków z pomocy udzielonej przez państwa członkowskie Europejskiego Porozumienia o Wolnym Handlu (EFTA) albo innych źródeł zagranicznych nie podlegających zwrotowi (W=1,5),\r\n- w ramach Narodowego Programu Rozwoju Humanistyki (W=0,5),\r\nkierownik i członkowie zespołu przygotowującego wniosek aplikacyjny otrzymują jednorazowo:\r\n1) 5×W punktów - za złożenie wniosku aplikacyjnego; punkty przyznawane jednorazowo na podstawie podziału dokonanego przez kierownika zespołu, proporcjonalnie do wkładu pracy,\r\n2) 30×W punktów - w przypadku otrzymania pozytywnej oceny formalno-merytorycznej złożonego wniosku; punkty przyznawane jednorazowo na podstawie podziału dokonanego przez kierownika zespołu, proporcjonalnie do wkładu pracy,\r\n3) 2 pkt. za każde 50 tys. zł przyznanych funduszy*, którego liderem jest Uczelnia lub inny podmiot należący do systemu szkolnictwa wyższego i nauki lub 2 pkt.za 25 tys. zł przyznanych funduszy*, którego liderem jest podmiot nienależący do systemu szkolnictwa wyższego i nauki × W punktów - za uzyskanie projektu; punkty mogą być rozdzielone proporcjonalnie do wkładu pracy w \r\nprzygotowanie wniosku w danym roku na podstawie podziału dokonanego przez kierownika zespołu\r\n* wartość projektu ogółem, jeżeli Uczelnia jest samodzielnym wykonawcą lub liderem, lub wartość realizowanych zadań, jeżeli Uczelnia jest członkiem konsorcjum\r\n", DzialID = 5, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Za udział w realizacji projektów obejmujących badania naukowe lub prace rozwojowe, pracach umownych, wdrożeniach i licencjach, pracownik uzyskuje 2 pkt. za każde 5 tys. zł wynagrodzenia brutto (wartość umowy z Uczelnią) z uwzględnieniem współczynnika „W” zależnego od źródła finansowania:\r\n1) przez Europejską Radę ds. Badań Naukowych (European Research Council) (W=5),\r\n2) w ramach programów ramowych w zakresie wspierania badań i innowacji Unii Europejskiej, albo w ramach programów związanych z wdrażaniem tych programów (W=2),\r\n3) przez instytucje zagraniczne lub organizacje międzynarodowe (W=1,5),\r\n4) ze środków funduszy strukturalnych Unii Europejskiej albo z niepodlegających zwrotowi środków z pomocy udzielonej przez państwa członkowskie Europejskiego Porozumienia o Wolnym Handlu (EFTA) albo innych źródeł zagranicznych nie podlegających zwrotowi (W=1,5),\r\n5) przez MNiSW, NCBR i NCN (W=1),\r\n6) w ramach Narodowego Programu Rozwoju Humanistyki (W=0,5)", DzialID = 5, IsOrganizational = false, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "1) Za złożenie wniosku o realizację projektu finansowanego w trybie konkursowym o wartości do 1 mln zł / powyżej 1 mln zł − kierownik dokonuje podziału 7/10 punktów proporcjonalnie do wkładu pracy zespołu;\r\n2) Za uzyskanie projektu zespół otrzymuje 2 pkt. za każde 50 tys. zł przyznanych funduszy*, którego liderem jest Uczelnia lub inny podmiot należący do systemu szkolnictwa wyższego i nauki lub 2 pkt. za 25 tys. zł przyznanych funduszy*, którego liderem jest podmiot nienależący do systemu szkolnictwa wyższego i nauki. Punkty mogą być przyznane jednorazowo lub proporcjonalnie do czasu \r\nrealizacji projektu w danym roku oraz podzielone proporcjonalnie do wkładu pracy w przygotowanie wniosku. Podział punktów dokonuje kierownik zespołu;\r\n3) Za udział w realizacji projektów pracownik uzyskuje 2 pkt. za każde 3 tys. zł wynagrodzenia brutto (wartość umowy z Uczelnią) \r\n* wartość projektu ogółem, jeżeli PB jest samodzielnym wykonawcą lub liderem, lub wartość realizowanych zadań, jeżeli Uczelnia jest członkiem konsorcjum", DzialID = 5, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Koordynator / koordynator wydziałowy lub koordynator zadania / członek zespołu w projekcie dydaktycznym lub inwestycyjnym finansowanym ze środków zewnętrznych (za każdy miesiąc) 4/2/1 pkt.", DzialID = 5, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Zajęcia dla studentów w ośrodku zagranicznym, m.in. w ramach programu „Erasmus+” - skierowanie z Uczelni - za 1 godz. – 1 pkt ", DzialID = 5, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Prowadzenie zajęć dydaktycznych w języku obcym w Uczelni - za 1 godz. – 1 pkt", DzialID = 5, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Wydziałowy koordynator programu „Erasmus+” / pełnomocnik dziekana ds. studiów międzynarodowych w zależności od liczby studentów pod opieką (jednorazowo, rocznie) 8 pkt. za każdych 10 studentów", DzialID = 5, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Koordynator programu „Erasmus+” w Studium Języków Obcych (jednorazowo, rocznie) 8 pkt", DzialID = 5, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Kierownik aktywnej, udokumentowanej rocznym sprawozdaniem, międzynarodowej umowy o współpracy naukowej (za każdy rok)8 pkt.", DzialID = 5, IsOrganizational = true, MaxPoints = "" });

            //Dział CSSDIR

            schematy.Add(new Schemat { Name = "Promotorstwo obronionej pracy dyplomowej inżynierskiej /  licencjackiej / magisterskiej (3 pkt za pracę)", DzialID = 6, IsOrganizational = true, MaxPoints = "3 pkt. za pracę" });
            schematy.Add(new Schemat { Name = "Opiekun roku studenckiego lub sekcji sportowej / opiekun praktyk studenckich jednego roku/opiekun studenckiego koła naukowego / opiekun zespołu dydaktycznego w Studium Języków Obcych/opiekun językowy powołany \r\ndo współpracy z wydziałem", DzialID = 6, IsOrganizational = true, MaxPoints = "4/4/8/8/8" });
            schematy.Add(new Schemat { Name = "Koordynator przedmiotu (w przypadku jeżeli przedmiot składa się z jednej / więcej niż jednej formy zajęć) ", DzialID = 6, IsOrganizational = true, MaxPoints = " 2/4" });
            schematy.Add(new Schemat { Name = "Członkostwo w komisjach / zespołach zadaniowych powołanych w celu opracowywania procedur i dokumentów służących doskonaleniu procesu dydaktycznego oraz zarządzania jednostką (4 pkt. dodatkowo za przewodniczenie komisjom i zespołom)", DzialID = 6, IsOrganizational = true, MaxPoints = "4" });
            schematy.Add(new Schemat { Name = "Promotorstwo wyróżnionych lub nagrodzonych prac dyplomowych \r\ni projektowych (poziom międzynarodowy / poziom krajowy / poziom regionalny / poziom uczelniany) ", DzialID = 6, IsOrganizational = true, MaxPoints = "25/15/8/4" });
            schematy.Add(new Schemat { Name = "Osiągnięcia (wyróżnienia, nagrody) studenckiego koła naukowego / koła zainteresowań w Liceum Ogólnokształcącym Politechniki Białostockiej \r\n(dalej zwanym LO PB), którego pracownik jest opiekunem – poziom międzynarodowy/poziom krajowy/poziom regionalny ", DzialID = 6, IsOrganizational = true, MaxPoints = "25/15/8" });
            schematy.Add(new Schemat { Name = "Organizacja międzynarodowej konferencji naukowej / dydaktycznej \r\n(w sumie max. 65 pkt.):\r\n- przewodniczący komitetu organizacyjnego;\r\n- sekretarz lub zastępca przewodniczącego komitetu organizacyjnego;\r\n- pozostali członkowie komitetu organizacyjnego;", DzialID = 6, IsOrganizational = true, MaxPoints = "do 30/do 20/do 15" });
            schematy.Add(new Schemat { Name = "Organizacja krajowej konferencji naukowej / dydaktycznej (w sumie max. 40 pkt.):\r\n- przewodniczący komitetu organizacyjnego;\r\n- sekretarz lub zastępca przewodniczącego komitetu organizacyjnego;\r\n- pozostali członkowie komitetu organizacyjnego", DzialID = 6, IsOrganizational = true, MaxPoints = "do 16/do 14/do 10" });
            schematy.Add(new Schemat { Name = "Organizacja konferencji studenckiej (w sumie max. 24 pkt.):\r\n- przewodniczący komitetu organizacyjnego;\r\n- sekretarz komitetu organizacyjnego;\r\n- pozostali członkowie komitetu organizacyjnego;", DzialID = 6, IsOrganizational = true, MaxPoints = "do 12/do 8/do 4" });
            schematy.Add(new Schemat { Name = "Przewodniczący komitetu naukowego konferencji lub przewodniczący konferencji – liczba punktów taka sama jak maksymalna dla sekretarza komitetu organizacyjnego, o którym mowa w pkt. VI.1-3", DzialID = 6, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Opiekun krajowej lub międzynarodowej studenckiej wyprawy, wycieczki, wymiany  naukowej lub dydaktycznej (za każdy dzień wyprawy), nie więcej niż 40 pkt.", DzialID = 6, IsOrganizational = true, MaxPoints = "4" });
            schematy.Add(new Schemat { Name = "Organizacja wycieczek dydaktycznych, konkursów studenckich, olimpiad przedmiotowych, uczelnianych rozgrywek sportowych/przeprowadzenie, sprawdzanie, koordynacja egzaminów zewnętrznych na zlecenie Uczelni \r\n(poza godzinami zajęć) – za każdą imprezę na wydziale/w Uczelni ", DzialID = 6, IsOrganizational = true, MaxPoints = "4/4" });
            schematy.Add(new Schemat { Name = "Opracowanie recenzji pracy dyplomowej (licencjackiej, inżynierskiej \r\nlub magisterskiej)", DzialID = 6, IsOrganizational = true, MaxPoints = "1 pkt za każdą recenzję,\r\nmax 12 pkt. za rok" });

            //Dział DJK

            schematy.Add(new Schemat { Name = "Autorstwo programu nowego przedmiotu na studiach pierwszego, drugiego i trzeciego stopnia, zaakceptowanego do realizacji przez Radę Wydziału (jednorazowo)", DzialID = 7, IsOrganizational = true, MaxPoints = "8" });
            schematy.Add(new Schemat { Name = "Autorstwo materiałów dydaktycznych realizowanych na zajęciach lub na platformie edukacyjnej – jednorazowo 8 punktów za każdy pakiet dydaktyczny*", DzialID = 7, IsOrganizational = true, MaxPoints = "8" });
            schematy.Add(new Schemat { Name = "Nowe stanowisko do zajęć laboratoryjnych lub program komputerowy do zajęć projektowych lub pracowni specjalistycznej (wraz z instrukcją laboratoryjną lub projektową, jednorazowo):\r\n- zaprojektowane i wykonane w Uczelni\r\n- zakupione i wdrożone \n (liczbę punktów dzieli się przez liczbę autorów z uwzględnieniem doktorantów)\r\n", DzialID = 7, IsOrganizational = true, MaxPoints = "od 15 do 25 / od 5 do 10" });
            schematy.Add(new Schemat { Name = "Przygotowanie raportu samooceny istniejącego kierunku, wniosku o uruchomienie nowego kierunku studiów lub o przyznanie nowych uprawnień do nadawania stopni naukowych \n (liczbę punktów dzieli się przez liczbę autorów z uwzględnieniem doktorantów)", DzialID = 7, IsOrganizational = true, MaxPoints = "80" });
            schematy.Add(new Schemat { Name = "Przygotowanie programu nowych studiów podyplomowych w Uczelni/kierowanie każdą edycją tych studiów \n (liczbę punktów dzieli się przez liczbę autorów z uwzględnieniem doktorantów)                                                      ", DzialID = 7, IsOrganizational = true, MaxPoints = "20/8" });
            schematy.Add(new Schemat { Name = "Przygotowanie programów nowych kursów dokształcających, kursów dla uczniów, studentów, pracowników i przedsiębiorców/prowadzenie każdej edycji kursów w Uczelni (w tym kursy na studiach podyplomowych) \n (liczbę punktów dzieli się przez liczbę autorów z uwzględnieniem doktorantów)", DzialID = 7, IsOrganizational = true, MaxPoints = "8/4" });
            schematy.Add(new Schemat { Name = "Przeprowadzanie egzaminów doktorskich z języka obcego, dyscypliny podstawowej i dodatkowej oraz egzaminu kwalifikacji językowej (za każdego przeegzaminowanego)", DzialID = 7, IsOrganizational = true, MaxPoints = "4" });
            schematy.Add(new Schemat { Name = "Ocena zajęć dydaktycznych równa uśrednionej ocenie z ankiet studenckich i doktoranckich za każdy rok w ocenianym okresie (oceny z ankiet studenckich w skali 5, 4, 3, 2, 1 przelicza się na punkty odpowiednio 15, 4, 0,-4,-15 i zaokrągla do liczby całkowitej)", DzialID = 7, IsOrganizational = true, MaxPoints = "" });
            schematy.Add(new Schemat { Name = "Ocena wyróżniająca/bardzo dobra zajęć dydaktycznych z uwzględnieniem arkuszy hospitacji (określa bezpośredni przełożony w uzgodnieniu z dziekanem)", DzialID = 7, IsOrganizational = true, MaxPoints = "8/4" });
            schematy.Add(new Schemat { Name = "Autorstwo egzaminu UCJ/przeprowadzenie sesji egzaminu TOEIC/UCJ", DzialID = 7, IsOrganizational = true, MaxPoints = "8/4" });
            schematy.Add(new Schemat { Name = "Bezpłatne prowadzenie zajęć z uczniami w ramach umów podpisanych ze szkołami ponadgimnazjalnymi (za każde 2 godziny zajęć)", DzialID = 7, IsOrganizational = true, MaxPoints = "2 nie więcej niż 16 na rok" });
            schematy.Add(new Schemat { Name = "Podniesienie kwalifikacji zawodowych (potwierdzone każdorazowo certyfikatem): doskonalenie warsztatu metodycznego poprzez udział w szkoleniach, kursach, konferencjach metodycznych, a także uzyskanie uprawnień do prowadzenia egzaminów certyfikowanych (np. TOEIC) ", DzialID = 7, IsOrganizational = true, MaxPoints = "4" });
            schematy.Add(new Schemat { Name = "Wykonanie przez pracownika SJO nieodpłatnych tłumaczeń dokumentów np. umowy o współpracy, publikacji, materiałów promocyjnych", DzialID = 7, IsOrganizational = true, MaxPoints = "4 pkt. za 1 stronę (max 10 stron)" });


            // Dział DP

            schematy.Add(new Schemat { Name = "Wydziałowy koordynator / współorganizator wydarzenia promującego Uczelnię, wydziały, kierunki kształcenia, jednostki uczelniane", DzialID = 8, IsOrganizational = true, MaxPoints = "8/4" });
            schematy.Add(new Schemat { Name = "Prowadzenie zajęć, wykładów, warsztatów o charakterze edukacyjnym, popularno-naukowym, w tym w ramach umów o współpracy ze szkołami, placówkami edukacyjnymi, kulturalnymi i samorządami", DzialID = 8, IsOrganizational = true, MaxPoints = "4" });
            schematy.Add(new Schemat { Name = "Udział w międzynarodowych / krajowych targach i spotkaniach edukacyjnych", DzialID = 8, IsOrganizational = true, MaxPoints = "8/4" });
            schematy.Add(new Schemat { Name = "Organizacja i udział w międzynarodowych / krajowych zawodach i imprezach sportowych", DzialID = 8, IsOrganizational = true, MaxPoints = "8/4" });
            schematy.Add(new Schemat { Name = "Wystąpienia i publikacje w mediach (telewizja, prasa, radio, Internet) w roli eksperta Uczelni lub gościa – uczestnika programu lub debaty", DzialID = 8, IsOrganizational = true, MaxPoints = "3" });
            schematy.Add(new Schemat { Name = "Wydziałowy koordynator / współorganizator wystawy i innych przedsięwzięć kulturalnych", DzialID = 8, IsOrganizational = true, MaxPoints = "8/4" });
            schematy.Add(new Schemat { Name = "Przedsięwzięcia organizacyjne – wizyta gości zagranicznych i krajowych w jednostce: prezentacja / opieka językowa / inne", DzialID = 8, IsOrganizational = true, MaxPoints = "2/4/2" });
            schematy.Add(new Schemat { Name = "Inne szczególne działania służące promocji i budowaniu pozytywnego wizerunku Uczelni (określa dziekan, kierownik jednostki)", DzialID = 8, IsOrganizational = true, MaxPoints = "max 12 pkt. za rok" });
       
            context.Dzials.AddRange(dzialy);
            context.Schematy.AddRange(schematy);

            context.SaveChanges();

        }

    }
}