//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod zosta³ wygenerowany przez narzêdzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mog¹ spowodowaæ nieprawid³owe zachowanie i zostan¹ utracone, jeœli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_SpecialLayout2.cshtml";
    ViewBag.UseSpecialNavbar = true;


#line default
#line hidden

#line 3 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Nazwa);


#line default
#line hidden

#line 4 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Data);


#line default
#line hidden

#line 5 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
    foreach (var item in Model)
    {
        

#line default
#line hidden

#line 6 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Nazwa);


#line default
#line hidden

#line 7 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Data);


#line default
#line hidden

#line 8 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Szczegoly);


#line default
#line hidden

#line 9 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Home\Index.cshtml"
             
    }

#line default
#line hidden
}
}
}
