//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod zosta³ wygenerowany przez narzêdzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mog¹ spowodowaæ nieprawid³owe zachowanie i zostan¹ utracone, jeœli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Edit_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Edit_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
  
    ViewBag.Title = "Edit";
 


#line default
#line hidden

#line 3 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
using (Html.BeginForm())
{
    

#line default
#line hidden

#line 4 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
   __o = Html.HiddenFor(model => model.PracownikID);


#line default
#line hidden

#line 8 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
       __o = Html.LabelFor(model => model.Imie, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 9 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.EditorFor(model => model.Imie, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 10 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" });


#line default
#line hidden

#line 11 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
       __o = Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 12 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 13 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" });


#line default
#line hidden

#line 14 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
       __o = Html.LabelFor(model => model.Stopien, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 15 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.EditorFor(model => model.Stopien, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 16 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.Stopien, "", new { @class = "text-danger" });


#line default
#line hidden

#line 17 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
       __o = Html.LabelFor(model => model.Tytul, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 18 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.EditorFor(model => model.Tytul, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 19 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.Tytul, "", new { @class = "text-danger" });


#line default
#line hidden

#line 20 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
       __o = Html.LabelFor(model => model.NumerTelefonu, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 21 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.EditorFor(model => model.NumerTelefonu, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 22 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
           __o = Html.ValidationMessageFor(model => model.NumerTelefonu, "", new { @class = "text-danger" });


#line default
#line hidden

#line 23 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
          
}

#line default
#line hidden

#line 24 "C:\Users\zymci\AppData\Local\Temp\041847F49CAF1E1D93321192B254BF2C84EE\3\ocenaokresowapracownikow\Views\Pracowniks\Edit.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
}
}
}
